version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run:
          name: Directory listing
          command: ls
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current dotnet version
          command: dotnet --version